### ISSUE TITLE
Update re3data plugin for RDMO 1.7.0 and higher

### ISSUE THREAD

**Issue by yvgrossmann** [rdmorganiser/rdmo-re3data#1]
Unfortunately the re3data plugin is not working anymore on RDMO 1.7.0 or higher. Because this plugin to query is quite a nice feature, it would be nice, if this can be adapted to the newer RDMO versions.

######
Our error report:

mod_wsgi (pid=3248599): Failed to exec Python script file '/config/wsgi.py'.
mod_wsgi (pid=3248599): Exception occurred processing WSGI script '/config/wsgi.py'.
Traceback (most recent call last):
File "/config/wsgi.py", line 7, in <module>
  application = get_wsgi_application()
File "/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
django.setup(set_prefix=False)
File "/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
File "/lib/python3.7/site-packages/django/conf/__init__.py", line 82, in
__getattr__
self._setup(name)
File "/lib/python3.7/site-packages/django/conf/__init__.py", line 69, in _setup
self._wrapped = Settings(settings_module)
File "/lib/python3.7/site-packages/django/conf/__init__.py", line 170, in __init__
mod = importlib.import_module(self.SETTINGS_MODULE) 
File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import 
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/config/settings/__init__.py", line 20, in <module> from .local import *
File "/config/settings/local.py", line 72, in <module>
('re3data', _('Repositories from re3data'), 'rdmo_re3data.Re3DataProvider')
NameError: name '_' is not defined

**Comment by jochenklar** [comment]
Hi @yvgrossmann, I found and fixed one problem, but it was not exactly the error given here. The line in `local.py` changed to 

```
OPTIONSET_PROVIDERS = [
    ('re3data', ('Repositories from re3data'), 'rdmo_re3data.providers.Re3DataProvider')
]
```
also `from django.utils.translation import gettext_lazy as _` might be missing at the top of the file.

**Comment by yvgrossmann** [comment]
great! Thanks a lot @jochenklar  👌 we'll have a look, if it works.
